app/models.py
#!/usr/bin/env python
#coding=utf8
from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import db
from . import login_manager

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    mailAdd = db.Column(db.String(64),primary_key=True)
    name = db.Column(db.String(32),nullable=False)
    passwd_hash = db.Column(db.String(128),nullable=False)
    age = db.Column(db.Integer,nullable=False)
    phone = db.Column(db.String(16),nullable=True)
    confirmed = db.Column(db.Boolean,nullable=False,default=False)

    @property
    def password(self):
        raise Exception('password is not a readable attribute')

    @password.setter
    def password(self,passwd):
        self.passwd_hash = generate_password_hash(passwd)

    def verify_passwd(self,password):
        return check_password_hash(self.passwd_hash,password)

    def get_id(self):
        return self.mailAdd

    def generate_confirmation_token(self):
        s = Serializer(current_app.config['SECRET_KEY'],expires_in=3600)
        return s.dumps({'confirm':self.mailAdd})

    def confirm_token(self,token):
        s = Serializer(current_app.config.get('SECRET_KEY'))
        try:
            data = s.loads(token)
        except Exception,e:
            return False
        if data.get('confirm') != self.mailAdd:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True


@login_manager.user_loader
def load_user(user_id):
    # print user_id
    return User.query.filter_by(mailAdd=user_id).first()
    # return

app/__init__.py
#!/usr/bin/env python
#coding=utf-8

from flask import Flask
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

from config import config

db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()

def create_app(config_mode=None):
    app = Flask(__name__)
    app.config.from_object(config.get(config_mode,'default'))
    config.get(config_mode,'default').init_app(app)

    db.init_app(app)
    bootstrap.init_app(app)

    login_manager.session_protection = 'strong'
    login_manager.login_view = 'auth.login' #TODO 这句语句设置了login的界面，后面所有@login_required的验证不通过时就跳转到这个界面
    login_manager.login_message = u'访问此页面需要登录'  #TODO 这句设置了当跳转过去之后显示的flash消息
    login_manager.init_app(app)

    from .main import main as main_blueprint
    from .auth import auth as authorization_blueprint

    app.register_blueprint(main_blueprint)
    app.register_blueprint(authorization_blueprint,url_prefix='/auth')

    return app

app/main/__init__.py
#!/usr/bin/env python
#coding=utf-8

from flask import Blueprint

main = Blueprint('main',__name__)

from . import views
from . import errors

app/main/views.py
#!/usr/bin/env python
#coding=utf8
'''
v1.0 modified@20170822
@author:weiyz

'''

from flask import render_template
from flask_login import login_required

from . import main

@main.route('/',methods=['GET'])
def index():
    return render_template('main/index.html')

@main.route('/userinfo',methods=['GET'])
@login_required
def show_userinfo():
    return render_template('main/userinfo.html')

app/templates/MyBase.html
{% extends 'bootstrap/base.html' %}
{% block navbar %}
    <nav class="navbar navbar-inverse">
    <div class="navbar-header">
        <a href="/" class="navbar-brand">用户系统</a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" >
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('auth.register') }}">注册</a></li>
            <li><a href="{{ url_for("main.show_userinfo") }}">用户信息</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
            {% else %}
            <li><a href="{{ url_for('auth.login') }}">登录</a></li>
            {% endif %}
        </ul>
    </div>
    </nav>
{% endblock %}

{% block content %}
<div class="container">
{% block head_message %}<h2>{% block head_message_content %}{% endblock %}</h2>{% endblock %}
<hr>
{% block page_content %}
{% endblock %}
</div>
{% endblock %}

app/templates/main/index.html
{% extends 'MyBase.html' %}
{% block title %}主页{% endblock %}
{% block head_message %}
    <h2 style="text-align: center">欢迎来到主页</h2>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert">&times</button>
    {{ message }}
    </div>
    {% endfor %}
{% endblock %}

app/templates/main/userinfo.html
{% extends 'MyBase.html' %}
{% block title %}用户信息{% endblock %}

{% block head_message %}当前用户信息{% endblock %}

{% block page_content %}
    <table class="table table-bordered table-hover">
    <caption>用户信息</caption>
    <tr>
        <th>字段名</th>
        <th>值</th>
    </tr>
    <tr>
        <td>姓名</td>
        <td>{{ current_user.name }}</td>
    </tr>
    <tr>
        <td>年龄</td>
        <td>{{ current_user.age }}</td>
    </tr>
    <tr>
        <td>联系电话</td>
        <td>{{ current_user.phone }}</td>
    </tr>
    </table>
{% endblock %}